### ISSUE TITLE
Facing issue in installing tailwind CSS to the code.

### ISSUE THREAD

**Issue by Abhinandan-4321** [kalviumcommunity/S59_Abhinandan_Capstone_Blogosphere#44]
wanted to install tailwind and flowbite React.
[Tailwind](https://tailwindcss.com/docs/guides/vite)
[Flowbite React](https://flowbite-react.com/)

Links for both the tailwind and Flowbite have been given above

**Comment by Abhinandan-4321** [comment]
Is there anyone who can help me with this?

**Comment by Satyamsharmahp36** [comment]
hi , can I start working on this ?

**Comment by Abhinandan-4321** [comment]
Yes.

**Comment by Satyamsharmahp36** [comment]
hi , you can review this PR [#45](https://github.com/kalviumcommunity/S59_Abhinandan_Capstone_Blogosphere/pull/45)
