### ISSUE TITLE
Facing issue in using Flowbite react

### ISSUE THREAD

**Issue by Abhinandan-4321** [kalviumcommunity/S59_Abhinandan_Capstone_Blogosphere#46]
So i am trying to install the FLowbite react tailwind CSS module. 
i am able to install it but if i am trying to use it it is coming with no css applied to it. I am not able to figure out what the issue is. 
can some one please help me with this? 🙏🙏
https://flowbite.com/docs/getting-started/react/
this is the link for the documentation to install this with which i tried.

**Comment by Abhinandan-4321** [comment]
I there anyone who can help me with this ?

**Comment by ananyatewari** [comment]
Hey

Can I work on this, please ?

**Comment by Abhinandan-4321** [comment]
Yes, go ahead.

**Comment by ananyatewari** [comment]
Hey

Can I work on this ?

**Comment by Abhinandan-4321** [comment]
Yes, go ahead.

**Comment by Abhinandan-4321** [comment]
Linking to PR #48
