### ISSUE TITLE
JWT Malformed on authentication

### ISSUE THREAD

**Issue by Abhinandan-4321** [kalviumcommunity/S59_Abhinandan_Capstone_Blogosphere#53]
so whenever i try to sign up sign in or logout
i am encountering jwt malformed error 
is there anyone who can help me with this?

**Comment by Merlinkk** [comment]
I faced a similar issue in my project as well. So can i work on this issue?

**Comment by Abhinandan-4321** [comment]
Yes sure.

**Comment by Abhinandan-4321** [comment]
Do you need my env for this issue to be solved?

**Comment by Abhinandan-4321** [comment]
I'll mail it to you.

**Comment by Merlinkk** [comment]
Issue solved. Review PR #54

**Comment by Abhinandan-4321** [comment]
i checked your PR. It is working fine now. Thanks.
